#!/usr/bin/env bash
# =============================================================================
# CoreBuilderVX — Main Entrypoint
# Adaptive local-first build engine | Termux + any POSIX shell
# =============================================================================
set -euo pipefail

CBX_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export CBX_ROOT

# Load config
source "$CBX_ROOT/config/default.conf"

# Load hardware profile (generated by detect.sh on first run)
if [[ -f "$CBX_ROOT/config/hardware.conf" ]]; then
    source "$CBX_ROOT/config/hardware.conf"
else
    "$CBX_ROOT/modules/hardware/detect.sh" --save
    source "$CBX_ROOT/config/hardware.conf"
fi

# Load internal API helpers
source "$CBX_ROOT/api/internal_api.sh"

# ---- Argument handling ------------------------------------------------------
usage() {
    cat <<EOF
CoreBuilderVX v${CBX_VERSION}

Usage: $(basename "$0") [command] [options]

Commands:
  menu          Launch interactive main menu (default)
  build         Run OS/project builder
  test          Run OS tester suite
  sim           Launch boot simulator
  vcloud        Launch Vcloud builder
  vm            Launch lightweight VM
  ai            Launch local AI runner
  update        Run self-upgrade module
  hardware      Show hardware profile
  frontend      Launch operator cockpit UI
  help          Show this help

Options:
  --no-color    Disable colour output
  --debug       Enable verbose debug output
  --version     Print version and exit

Examples:
  $0                  # interactive menu
  $0 build            # OS builder
  $0 test integrity   # integrity test only
EOF
}

main() {
    local cmd="${1:-menu}"
    shift || true

    case "$cmd" in
        menu)       source "$CBX_ROOT/menus/main_menu.sh" ;;
        build)      source "$CBX_ROOT/modules/os_builder/blueprint.sh" "$@" ;;
        test)       source "$CBX_ROOT/modules/os_tester/integrity.sh"  "$@" ;;
        sim)        source "$CBX_ROOT/modules/boot_sim/simulate.sh"     "$@" ;;
        vcloud)     source "$CBX_ROOT/modules/vcloud/build.sh"          "$@" ;;
        vm)         source "$CBX_ROOT/modules/vm/lite_vm.sh"            "$@" ;;
        ai)         source "$CBX_ROOT/modules/ai_runner/local_ai.sh"    "$@" ;;
        update)     source "$CBX_ROOT/modules/updater/self_upgrade.sh"  "$@" ;;
        hardware)   source "$CBX_ROOT/modules/hardware/detect.sh"       "$@" ;;
        frontend)   source "$CBX_ROOT/modules/frontend/serve.sh"        "$@" ;;
        --version|-v) cbx_info "CoreBuilderVX v${CBX_VERSION}" ;;
        --no-color)  CBX_NO_COLOR=1; main menu ;;
        help|--help|-h) usage ;;
        *) cbx_error "Unknown command: $cmd"; usage; exit 1 ;;
    esac
}

main "$@"
