#!/usr/bin/env bash
# =============================================================================
# CoreBuilderVX — Setup Wizard
# First-time configuration for hardware, paths, backend, and preferences
# =============================================================================

CBX_ROOT="${CBX_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
source "$CBX_ROOT/api/internal_api.sh"

setup_wizard() {
    clear
    cbx_banner "Setup Wizard"
    cbx_header "First-Time Configuration"
    echo ""
    cbx_info "This wizard will configure CoreBuilderVX for your device."
    echo ""

    # ---- Step 1: Hardware detection -----------------------------------------
    cbx_step "Step 1 of 5 — Hardware Detection"
    if cbx_confirm "Run hardware detection now?"; then
        bash "$CBX_ROOT/modules/hardware/detect.sh" --save
        cbx_ok "Hardware profile saved"
    else
        cbx_warn "Skipped — using defaults"
    fi
    echo ""

    # ---- Step 2: Backend preference -----------------------------------------
    cbx_step "Step 2 of 5 — Backend Engine"
    echo -e "  ${C_CYAN}1${C_NC}  Auto-detect (recommended)"
    echo -e "  ${C_CYAN}2${C_NC}  Python (Flask)"
    echo -e "  ${C_CYAN}3${C_NC}  Node.js (Express)"
    echo -e "  ${C_CYAN}4${C_NC}  None (shell-only mode)"
    echo ""
    read -r -p "  Select [1]: " be_choice
    case "${be_choice:-1}" in
        2) BACKEND="python" ;;
        3) BACKEND="node"   ;;
        4) BACKEND="none"   ;;
        *) BACKEND="auto"   ;;
    esac
    cbx_ok "Backend set to: $BACKEND"
    echo ""

    # ---- Step 3: API port ----------------------------------------------------
    cbx_step "Step 3 of 5 — API Port"
    local port
    port="$(cbx_prompt "API port" "8765")"
    cbx_ok "API port set to: $port"
    echo ""

    # ---- Step 4: Data directory ----------------------------------------------
    cbx_step "Step 4 of 5 — Data Directory"
    local data_dir
    data_dir="$(cbx_prompt "Data directory" "$CBX_ROOT/data")"
    mkdir -p "$data_dir"
    cbx_ok "Data directory: $data_dir"
    echo ""

    # ---- Step 5: Auto-update -----------------------------------------------------------------
    cbx_step "Step 5 of 5 — Auto-Update"
    local auto_update=0
    if cbx_confirm "Enable auto-update check on launch?"; then
        auto_update=1
    fi
    cbx_ok "Auto-update: $( [[ $auto_update -eq 1 ]] && echo enabled || echo disabled)"
    echo ""

    # ---- Write user config ---------------------------------------------------
    cat > "$CBX_ROOT/config/user.conf" <<EOF
# CoreBuilderVX User Configuration
# Generated by setup wizard — $(date '+%Y-%m-%d %H:%M:%S')
CBX_BACKEND="$BACKEND"
CBX_API_PORT="$port"
CBX_DATA_DIR="$data_dir"
CBX_AUTO_UPDATE="$auto_update"
EOF

    cbx_ok "Configuration saved to config/user.conf"
    echo ""
    cbx_info "Setup complete! Run ./core.sh or cbx to launch."
    echo ""
    cbx_pause
}

setup_wizard
